services:
  whisper-api:
    build: .
    container_name: whisper-api
    ports:
      - "9000:9000"
    volumes:
      - whisper_models:/app/models  # volumen persistente para modelos

volumes:
  whisper_models:
